### PR TITLE
fix(): backgroundImage/overlayImage erasable

### PR DESCRIPTION
**Pull request by yasupeke**
I always appreciate the convenience of using this tool. I have fixed an issue where the erasable setting for backgroundImage/overlayImage was not being applied. Please review the changes.

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
I understand where this is coming from.
The fabric bindings are supposed to set erasable to true by default and it seems it does not.
That is IMO where you should be looking. I recall fabric introducing a breaking change regarding default props without announcing it.

**Comment by yasupeke** [comment]
Thank you for your response.
I believe the eraser functionality has been removed from fabric and is now handled by Erase2d, which is why erasable has been removed.
Should we request fabric to add the erasable property?

**Comment by ShaMan123** [comment]
Indeed, I removed it.
I meant we can set a default value of erasable true on FabticObject

**Comment by ShaMan123** [comment]
Try this


FabricObject.ownDefaults.erasable = true

**Comment by yasupeke** [comment]
I tried FabricObject.ownDefaults.erasable = true. However, even after setting this, the image set as canvas.backgroundImage still gets erased when erasable = false.

**Comment by ShaMan123** [comment]
I am no longer part of fabric so I can't say if tge latest version has no related bugs

**Comment by ShaMan123** [comment]
My bad!!
I misunderstood.
So it seems you are correct with this pr.

**Comment by ShaMan123** [comment]
Sorry again. I reviewed to pr again and now I get it.
I would simply remove the === undefined condition so that it passes only if the object is erasable.
Good catch and sorry again.

**Comment by ShaMan123** [comment]
You are correct about walk as well.
https://github.com/ShaMan123/erase2d/blob/21b5233e224ec381f4a7b9bfb477d591b36deee1/packages/fabric/src/EraserBrush.ts#L399


It is a question if the end event should handle them as well....
But for know this pr is good enough after removing what I requested.

**Comment by yasupeke** [comment]
Thank you for confirming. 
Currently, users of Erase2d can erase canvas.backgroundImage and canvas.overlayImage if erasable is not set. If we remove the === undefined check, the behavior will change for current users. Is it okay to remove it?

**Comment by ShaMan123** [comment]
Yes, you found a bug, this is the fix.

I want it to comply with existing logic found in walk

https://github.com/ShaMan123/erase2d/blob/21b5233e224ec381f4a7b9bfb477d591b36deee1/packages/fabric/src/EraserBrush.ts#L24-L34

Only if strictly erasable does it collect the object.

**Comment by ShaMan123** [comment]
I just reviewed the commit method.
I think we should pass the overlay/bg images in the args, maybe as part of targets.
Then, from the end event, alongside the walk call we can place the code that currently resides in commit so that if the event is prevented the user has the images as well.
I guess I forgot about this or decided i  the past to remove it because I didn't like how overlayImage is implemented in fabric.

These thoughts can wait...

Thanks for your time and contribution!

**Review by ShaMan123 — APPROVED** [review]

**Comment by ShaMan123** [comment]
v1.1.7 is published to npm with your fix. Thanks!

**Pull request merged**
